### PR TITLE
Project submitted

### PR DESCRIPTION
**Pull request by reifnotreef**

### CODE REVIEW

**Comment by randallreedjr** [comment]
@reifnotreef It looks like the executable is missing?

**Comment by reifnotreef** [comment]
@randallreedjr 
Hey Randall,
I did a reformat after finishing this assignment and I think I forgot to push my final changes that included my cli! I should be able to finish rewriting it today.

**Comment by randallreedjr** [comment]
Great!

**Comment by randallreedjr** [comment]
@reifnotreef Closing this PR for now. Feel free to reopen or resubmit.

**Pull request closed without merging**
