### PR TITLE
Done

### PR DESCRIPTION
**Pull request by morgvanny**

### CODE REVIEW

**Comment by randallreedjr** [comment]
@aviflombaum This pull request is difficult to review because of the number of files included; any advice?

**Comment by morgvanny** [comment]
@randallreedjr I don't really know how/why that happened. I only consciously changed a few files

**Comment by randallreedjr** [comment]
@morgvanny I might have an idea on how to clear up this repository. Could you add me as a collaborator?
* Visit https://github.com/morgvanny/ttt-with-ai-project-v-000/settings/collaboration and add `randallreedjr` in the 'Collaborator' section.
I should automatically get a notification when this is done, but you can also ping me here if you would like.

**Comment by randallreedjr** [comment]
@morgvanny Please see https://github.com/learn-co-students/ttt-with-ai-project-v-000/pull/59 for comments.

**Pull request closed without merging**
