### PR TITLE
Jacobsb

### PR DESCRIPTION
**Pull request by corya0687**

### CODE REVIEW

**Comment by randallreedjr** [comment]
Hi @corya0687 and @jj54321. There were some extra files included in your submissions that make it difficult to review your code. Could you remove the `.bundle` directory and resubmit?
Alternatively, you can add me as a collaborator to your repo and I'll take care of it for you.
* Visit https://github.com/coltonstaab1/ttt-with-ai-project-v-000/settings/collaboration and add `randallreedjr` in the 'Collaborator' section.
Also, it looks like you worked together on this project as a team. Can you let me know which project submission you would prefer I review? Thanks!

**Comment by randallreedjr** [comment]
Also I would be happy to review both submissions if they are sufficiently different.

**Comment by jj54321** [comment]
Thanks for taking a look. I believe I just added you as a collaborator so
feel free to do whatever you think needs doing.

We last submitted from Cory's branch wich was corysb but we then merged to
master. So the master branch should be the final code.

**Comment by corya0687** [comment]
Thanks

**Comment by randallreedjr** [comment]
Closing. Will review #66.

**Pull request closed without merging**
