### PR TITLE
Done

### PR DESCRIPTION
**Pull request by coltonstaab1**

### CODE REVIEW

**Comment by randallreedjr** [comment]
Hi @coltonstaab1. There were some extra files included in your submission that make it difficult to review your code. Could you remove the `.bundle` directory and resubmit?
Alternatively, you can add me as a collaborator to your repo and I'll take care of it for you.
* Visit https://github.com/coltonstaab1/ttt-with-ai-project-v-000/settings/collaboration and add `randallreedjr` in the 'Collaborator' section.

**Comment by coltonstaab1** [comment]
Hi Randall,

I added you to my repository. Let me know if you have any questions!

Colton

**Comment by randallreedjr** [comment]
@coltonstaab1 Please see https://github.com/learn-co-students/ttt-with-ai-project-v-000/pull/64 for comments on your project. Closing this PR.

**Comment by coltonstaab1** [comment]
Great, thank you Randall!

**Pull request closed without merging**
